# Generated by Django 5.0.1 on 2024-01-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_rename_precio_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='id_objeto',
        ),
    ]
